# Applied Linear Algebra


**Outcomes**

- Refresh some important linear algebra concepts  
- Apply concepts to understanding unemployment and pricing portfolios  
- Use `numpy` to do linear algebra operations  

## Outline

- [Applied Linear Algebra](#Applied-Linear-Algebra)  
  - [Vectors and Matrices](#Vectors-and-Matrices)  
  - [Portfolios](#Portfolios)  


In [76]:
# import numpy to prepare for code below
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
# activate plot theme



## Vectors and Matrices

### Vectors

A (N-element) vector is $ N $ numbers stored together.

We typically write a vector as $ x = \begin{bmatrix} x_1 \\ x_2 \\ \dots \\ x_N \end{bmatrix} $.

In numpy terms, a vector is a 1-dimensional array.



  
In a previous lecture, we saw some types of operations that can be done on
vectors, such as

In [77]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

**Element-wise operations**: Let $ z = x ? y $ for some operation $ ? $, one of
the standard *binary* operations ($ +, -, \times, \div $). Then we can write
$ z = \begin{bmatrix} x_1 ? y_1 & x_2 ? y_2 \end{bmatrix} $. Element-wise operations require
that $ x $ and $ y $ have the same size.

In [78]:
print("Element-wise Addition", x + y)
print("Element-wise Subtraction", x - y)
print("Element-wise Multiplication", x * y)
print("Element-wise Division", x / y)

Element-wise Addition [5 7 9]
Element-wise Subtraction [-3 -3 -3]
Element-wise Multiplication [ 4 10 18]
Element-wise Division [0.25 0.4  0.5 ]


**Scalar operations**: Let $ w = a ? x $ for some operation $ ? $, one of the
standard *binary* operations ($ +, -, \times, \div $). Then we can write
$ w = \begin{bmatrix} a ? x_1 & a ? x_2 \end{bmatrix} $.

In [79]:
print("Scalar Addition", 3 + x)
print("Scalar Subtraction", 3 - x)
print("Scalar Multiplication", 3 * x)
print("Scalar Division", 3 / x)

Scalar Addition [4 5 6]
Scalar Subtraction [2 1 0]
Scalar Multiplication [3 6 9]
Scalar Division [3.  1.5 1. ]


Another operation very frequently used in data science is the **dot product**.

The dot between $ x $ and $ y $ is written $ x \cdot y $ and is
equal to $ \sum_{i=1}^N x_i y_i $.

In [80]:
print("Dot product", np.dot(x, y))

Dot product 32


We can also use `@` to denote dot products (and matrix multiplication which we’ll see soon!).

In [81]:
print("Dot product with @", x @ y)

Dot product with @ 32


### Matrices

An $ N \times M $ matrix can be thought of as a collection of M
N-element vectors stacked side-by-side as columns.

We write a matrix as

$$
\begin{bmatrix} x_{11} & x_{12} & \dots & x_{1M} \\
                x_{21} & \dots & \dots & x_{2M} \\
                \vdots & \vdots & \vdots & \vdots \\
                x_{N1} & x_{N2} & \dots & x_{NM}
\end{bmatrix}
$$

In numpy terms, a matrix is a 2-dimensional array.

We can create a matrix by passing a list of lists to the `np.array` function.

In [82]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ones((2, 3))
z = np.array([[1, 2], [3, 4], [5, 6]])

We can perform element-wise and scalar operations as we did with vectors. In fact, we can do
these two operations on arrays of any dimension.

In [83]:
print("Element-wise Addition\n", x + y)
print("Element-wise Subtraction\n", x - y)
print("Element-wise Multiplication\n", x * y)
print("Element-wise Division\n", x / y)

print("Scalar Addition\n", 3 + x)
print("Scalar Subtraction\n", 3 - x)
print("Scalar Multiplication\n", 3 * x)
print("Scalar Division\n", 3 / x)

Element-wise Addition
 [[2. 3. 4.]
 [5. 6. 7.]]
Element-wise Subtraction
 [[0. 1. 2.]
 [3. 4. 5.]]
Element-wise Multiplication
 [[1. 2. 3.]
 [4. 5. 6.]]
Element-wise Division
 [[1. 2. 3.]
 [4. 5. 6.]]
Scalar Addition
 [[4 5 6]
 [7 8 9]]
Scalar Subtraction
 [[ 2  1  0]
 [-1 -2 -3]]
Scalar Multiplication
 [[ 3  6  9]
 [12 15 18]]
Scalar Division
 [[3.   1.5  1.  ]
 [0.75 0.6  0.5 ]]


Similar to how we combine vectors with a dot product, matrices can do what we’ll call *matrix
multiplication*.

Matrix multiplication is effectively a generalization of dot products.

**Matrix multiplication**: Let $ v = x \cdot y $ then we can write
$ v_{ij} = \sum_{k=1}^N x_{ik} y_{kj} $ where $ x_{ij} $ is notation that denotes the
element found in the ith row and jth column of the matrix $ x $.

The image below from [Wikipedia](https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram.svg),
by Bilou, shows how matrix multiplication simplifies to a series of dot products:

<img src="https://datascience.quantecon.org/assets/_static/applied_linalg_files/mat_mult_wiki_bilou.png" alt="matmult.png" style="">

  
After looking at the math and image above, you might have realized that matrix
multiplication requires very specific matrix shapes!

For two matrices $ x, y $ to be multiplied, $ x $
must have the same number of columns as $ y $ has rows.

Formally, we require that for some integer numbers, $ M, N, $ and $ K $
that if $ x $ is $ N \times M $ then $ y $ must be $ M \times
K $.

If we think of a vector as a $ 1 \times M $ or $ M \times 1 $ matrix, we can even do
matrix multiplication between a matrix and a vector!

Let’s see some examples of this.

In [84]:
x1 = np.reshape(np.arange(6), (3, 2))
x2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
x3 = np.array([[2, 5, 2], [1, 2, 1]])
x4 = np.ones((2, 3))

y1 = np.array([1, 2, 3])
y2 = np.array([0.5, 0.5])

Numpy allows us to do matrix multiplication in three ways.

In [85]:
print("Using the matmul function for two matrices")
print(np.matmul(x1, x4))
print("Using the dot function for two matrices")
print(np.dot(x1, x4))
print("Using @ for two matrices")
print(x1 @ x4)

Using the matmul function for two matrices
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
Using the dot function for two matrices
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
Using @ for two matrices
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [86]:
print("Using the matmul function for vec and mat")
print(np.matmul(y1, x1))
print("Using the dot function for vec and mat")
print(np.dot(y1, x1))
print("Using @ for vec and mat")
print(y1 @ x1)

Using the matmul function for vec and mat
[16 22]
Using the dot function for vec and mat
[16 22]
Using @ for vec and mat
[16 22]


Despite our options, we stick to using `@` because
it is simplest to read and write.



### Other Linear Algebra Concepts

#### Transpose

A matrix transpose is an operation that flips all elements of a matrix along the diagonal.

More formally, the $ (i, j) $ element of $ x $ becomes the $ (j, i) $ element of
$ x^T $.

In particular, let $ x $ be given by

$$
x = \begin{bmatrix} 1 & 2 & 3 \\
                    4 & 5 & 6 \\
                    7 & 8 & 9 \\
    \end{bmatrix}
$$

then $ x $ transpose, written as $ x' $, is given by

$$
x = \begin{bmatrix} 1 & 4 & 7 \\
                    2 & 5 & 8 \\
                    3 & 6 & 9 \\
    \end{bmatrix}
$$

In Python, we do this by

In [87]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("x transpose is")
print(x.transpose())

x transpose is
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### Identity Matrix

In linear algebra, one particular matrix acts very similarly to how 1 behaves for scalar numbers.

This matrix is known as the *identity matrix* and is given by

$$
I = \begin{bmatrix} 1  & 0 & 0 & \dots & 0 \\
                    0 & 1 & 0 & \dots & 0 \\
                    \vdots & \vdots & \ddots & \vdots & \vdots \\
                    0 & 0 & 0 & \dots & 1
    \end{bmatrix}
$$

As seen above, it has 1s on the diagonal and 0s everywhere else.

When we multiply any matrix or vector by the identity matrix, we get the original matrix or vector
back!

Let’s see some examples.

In [88]:
I = np.eye(3)
x = np.reshape(np.arange(9), (3, 3))
y = np.array([1, 2, 3])

print("I @ x", "\n", I @ x)
print("x @ I", "\n", x @ I)
print("I @ y", "\n", I @ y)
print("y @ I", "\n", y @ I)

I @ x 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
x @ I 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
I @ y 
 [1. 2. 3.]
y @ I 
 [1. 2. 3.]


#### Inverse (optional on first pass, required for Chapter 10)

If you recall, you learned in your primary education about solving equations for certain variables.

For example, you might have been given the equation

$$
3x + 7 = 16
$$

and then asked to solve for $ x $.

You probably did this by subtracting 7 and then dividing by 3.

Now let’s write an equation that contains matrices and vectors.

$$
\begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}
$$

How would we solve for $ x = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} $?

Unfortunately, there is no “matrix divide” operation that does the opposite of matrix multiplication.

Instead, we first have to do what’s known as finding the inverse. We must multiply both sides by this inverse to solve.

Consider some matrix $ A $.

The inverse of $ A $, given by $ A^{-1} $, is a matrix such that $ A A^{-1} = I $
where $ I $ is our identity matrix.

Notice in our equation above, if we can find the inverse of
$ \begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix} $ then we can multiply both sides by the inverse
to get

$$
\begin{align*}
\begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix}^{-1}\begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} &= \begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix}^{-1}\begin{bmatrix} 3 \\ 4 \end{bmatrix} \\
I \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} &= \begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix}^{-1} \begin{bmatrix} 3 \\ 4 \end{bmatrix} \\
 \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} &= \begin{bmatrix} 1 & 2 \\ 3 & 1 \end{bmatrix}^{-1} \begin{bmatrix} 3 \\ 4 \end{bmatrix}
\end{align*}
$$

Computing the inverse requires that a matrix be square and satisfy some other conditions
(non-singularity) that are beyond the scope of this lecture.

We also skip the exact details of how this inverse is computed, but, if you are interested,
you can visit the
[QuantEcon Linear Algebra lecture](https://lectures.quantecon.org/py/linear_algebra.html)
for more details.

We demonstrate how to compute the inverse with numpy below.

In [89]:
# This is a square (N x N) non-singular matrix
A = np.array([[1, 2, 0], [3, 1, 0], [0, 1, 2]])

print("This is A inverse")

print(np.linalg.inv(A))

print("Check that A @ A inverse is I")
print(np.linalg.inv(A) @ A)

This is A inverse
[[-0.2  0.4  0. ]
 [ 0.6 -0.2  0. ]
 [-0.3  0.1  0.5]]
Check that A @ A inverse is I
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  0.00000000e+00  1.00000000e+00]]


## Portfolios



Vectors and inner products give us a convenient way to organize and calculate the value of portfolios of assets

### Static Payoffs

As an example, consider a portfolio with 4 units of asset A, 2.5 units of asset B, and 8 units of
asset C.

At a particular point in time, the assets pay the following dvidends $ 3 $/unit of asset A, $ 5 $/unit of B, and
$ 1.10 $/unit of C.

First, calculate the value of dividends  earned by this portfolio directly with a sum.

In [90]:
4.0 * 3.0 + 2.5 * 5.0 + 8 * 1.1

33.3

We can make this more convenient and general by using arrays for accounting, and then sum then in a
loop.

In [91]:
import numpy as np
x = np.array([4.0, 2.5, 8.0]) # portfolio units
y = np.array([3.0, 5.0, 1.1]) # payoffs
n = len(x)
p = 0.0
for i in range(n): # i.e. 0, 1, 2
    p = p + x[i] * y[i]

p

33.3

The above would have worked with `x` and `y` as `list` rather than `np.array`.

Note that the general pattern above is the sum.

$$
p = \sum_{i=0}^{n-1} x_i y_i = x \cdot y
$$

This is an inner product as implemented by the `np.dot` function

In [92]:
x @ y

33.3

This approach allows us to simultaneously price different portfolios by stacking them in a matrix and using the dot product (the `@` operator does the dot product for us!).

In [93]:
y = np.array([3.0, 5.0, 1.1]) # payoffs
x1 = np.array([4.0, 2.5, 8.0]) # portfolio 1
x2 = np.array([2.0, 1.5, 0.0]) # portfolio 2
X = np.array((x1, x2))

# calculate with inner products
p1 = X[0,:] @ y
p2 = X[1,:] @ y
print("Calculating separately")
print([p1, p2])

# or with a matrix multiplication
print("Calculating with matrices")
P = X @ y
print(P)

Calculating separately
[33.3, 13.5]
Calculating with matrices
[33.3 13.5]


Insight: If you substitute dividends by returns and number of shares by portfolio weights, this same formulation allow us to easily compute the returns of a portfolio

$$
r = \sum_{i=0}^{n-1} w_i r_i = w \cdot r
$$
